Add a call of assert_vars() for both min_dates and max_dates to check…
Roche-GSK/admiral pull request #594
Opened 2021-10-13 14:39 UTC by hamzarahal

… that must be a list of variable names

2021-10-15 12:34 UTC, thomas-neitmann requested changes

2021-10-15 12:34 UTC, thomas-neitmann commented on R/derive_date_vars.R
>  #'   ),
Only make the change when `derive_vars_dt()` or `derive_vars_dtm()` is called but **not** for `impute_dtc()`.

2021-11-02 06:53 UTC, hamzarahal commented on R/derive_date_vars.R
> +    )
Updated for derive_vars_dtm() code

2021-11-02 07:06 UTC, hamzarahal commented
@thomas-neitmann may need to check again for the related vignettes and see if the updates are well implemented? because the PR fail is still coming from vignettes

2021-11-09 11:01 UTC, hamzarahal commented
@thomas-neitmann  I have updated for both test-impute_dtc.R and imputation.Rmd to change vars by list when we call the min/max dates parameters for impute_dtc() call, also checked for the ones using impute_dtc that list() is present whenever we call min/max dates,

2021-11-09 12:44 UTC, thomas-neitmann commented
Thanks @hamzarahal! There's still a case where `vars()` is being used inside `impute_dtc()`, namely in the example of that function. 
![image](https://user-images.githubusercontent.com/11788080/140926371-384aecfb-2f89-489e-b0b2-fd39e10ec644.png)

2021-11-09 15:13 UTC, hamzarahal commented
@thomas-neitmann That means that the issue is still coming from man/imputec_dtc, since when checking derive_date_vars() the update is implemented yet, if it's the case need to commit/push only that file?

<img width="489" alt="Capture d’écran 2021-11-09 161258" src="https://user-images.githubusercontent.com/7486109/140950767-7925069c-2700-46dc-81e8-11a89bf0a006.png">

2021-11-09 16:20 UTC, thomas-neitmann commented
You can to run `devtools::document()` and then commit the changes file in the `man` folder.

2021-11-10 12:51 UTC, thomas-neitmann approved these changes
Thanks!

2021-11-10 12:51 UTC, merged