738 update derive var naming convention
Roche-GSK/admiral pull request #756
Opened 2021-12-15 20:38 UTC by amsmith214

Functions, examples, example scripts, vignettes are updated for 

- `derive_disposition_dt()`, `derive_disposition_status()`, `derive_extreme_flag`, `derive_worst_flag`, `derive_last_dose`, `derive_obs_number`, `derive_disposition_reason` 

to reflect naming changes to 

- `derive_var_disposition_dt()`, `derive_var_disposition_status()`, `derive_var_extreme_flag`, `derive_var_worst_flag`, `derive_var_last_dose`, `derive_var_obs_number`, `derive_vars_disposition_reason` 

respectively. Deprecation warnings added to documentation for affected functions. Sorry for the deletion/addition, this seems like an artifact of my machine's Rstudio git interface being incredibly slow.

2021-12-15 20:51 UTC, amsmith214 commented
will fix the failed check tomorrow

2021-12-17 11:31 UTC, bundfussr requested changes
Nice work!

- `derive_agegr_fda()` and  `derive_agegr_ema()` should be renamed as well.
- Line 228 in adsl.Rmd should be updated. ("derive_disposition_status(")
- Line 297 in adsl.Rmd should be updated. ("derive_disposition_reason(")
- Line 540 in bds_finding.Rmd should be updated. ("Note: Additional examples of the `derive_extreme_flag()` function can be")
- Line 581in bds_tte.Rmd should be updated. ("The admiral function `derive_obs_number()` can be used to derive `ASEQ`:")
- Line 234 in occds.Rmd should be updated. ("The function `derive_last_dose()` can be used to derive the last dose date before the start of the event. ")
- Line 349 in occds.Rmd should be updated. ("The function `derive_extreme_flag()` can help derive variables such as `AOCCIFL`,")
- Line 101in unit_test_guidance.Rmd should be updated. ("your function justifies it, e.g. see the test script: https://github.com/Roche-GSK/admiral/blob/master/tests/testthat/test-derive_extreme_flag.R.")

2021-12-17 12:09 UTC, amsmith214 commented
> Nice work!
> 
> * `derive_agegr_fda()` and  `derive_agegr_ema()` should be renamed as well.
> * Line 228 in adsl.Rmd should be updated. ("derive_disposition_status(")
> * Line 297 in adsl.Rmd should be updated. ("derive_disposition_reason(")
> * Line 540 in bds_finding.Rmd should be updated. ("Note: Additional examples of the `derive_extreme_flag()` function can be")
> * Line 581in bds_tte.Rmd should be updated. ("The admiral function `derive_obs_number()` can be used to derive `ASEQ`:")
> * Line 234 in occds.Rmd should be updated. ("The function `derive_last_dose()` can be used to derive the last dose date before the start of the event. ")
> * Line 349 in occds.Rmd should be updated. ("The function `derive_extreme_flag()` can help derive variables such as `AOCCIFL`,")
> * Line 101in unit_test_guidance.Rmd should be updated. ("your function justifies it, e.g. see the test script: https://github.com/Roche-GSK/admiral/blob/master/tests/testthat/test-derive_extreme_flag.R.")

Thanks, and sorry for missing so many instances. Do we have an elegant way of finding instances of deprecated function names in the documentation, or is it down to using the GH search?

2021-12-17 12:28 UTC, bundfussr commented
I used `grep -P 'derive_(obs|last|wor|disp|extr)' *.Rmd` in the terminal.

2021-12-17 12:38 UTC, amsmith214 commented
> I used `grep -P 'derive_(obs|last|wor|disp|extr)' *.Rmd` in the terminal.

regex to the rescue!

2021-12-17 16:45 UTC, amsmith214 commented on R/derive_var_disposition_dt.R
> +  new_var <- assert_symbol(enquo(new_var))
done and tested on examples from documentation

2021-12-17 16:45 UTC, amsmith214 commented on R/derive_var_disposition_status.R
> +  deprecate_warn("0.6.0", "derive_disposition_status()", "derive_var_disposition_status()")
done and tested on examples from documentation

2021-12-17 16:45 UTC, amsmith214 commented on R/derive_var_extreme_flag.R
> +  if (!missing(flag_filter)) {
done and tested on examples from documentation

2021-12-17 16:46 UTC, amsmith214 commented on R/derive_var_extreme_flag.R
> +
warning added

2021-12-17 16:46 UTC, amsmith214 commented on R/derive_var_last_dose.R
> +  deprecate_warn("0.6.0", "derive_last_dose()", "derive_var_last_dose()")
done and tested on examples from documentation

2021-12-17 16:46 UTC, amsmith214 commented on R/derive_var_obs_number.R
> +  # checks and quoting
done and tested on examples from documentation

2021-12-17 16:46 UTC, amsmith214 commented on R/derive_vars_disposition_reason.R
> +  deprecate_warn("0.6.0", "derive_disposition_reason()", "derive_vars_disposition_reason()")
done and tested on examples from documentation

2021-12-20 08:35 UTC, thomas-neitmann commented
There are several lintr annotations. Please fix these issues (you can run `lintr::lint_package()` locally to get a nice overview). Otherwise this looks good to me 👍

2021-12-22 08:35 UTC, thomas-neitmann commented
@amsmith214 There's a merge conflict that needs to be taken care off before we can merge this PR into `devel`. Please resolve locally in RStudio. The git guidance vignette should be helpful. Please refer to the version on the `devel` branch.

2022-01-10 15:01 UTC, thomas-neitmann approved these changes

2022-01-10 15:06 UTC, thomas-neitmann commented
@bundfussr Please approve as well if this looks good to you. Without your approval merging is currently blocked.

2022-01-10 15:17 UTC, bundfussr approved these changes

2022-01-10 15:31 UTC, merged